# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true #not used since Jekyll v3.0

# Setup
title:               Luc Geurts
tagline:             'Amazon Web Services, BunsenLabs Linux, Coding, Xperf'
description:         'Midnight musings of a former PFE.'
url:                 http://lgeurts.github.io
baseurl:             ''
#plugins: 			        [jekyll-paginate]
paginate:            5
paginate_path: 		 "page:num"

# About/contact
author:
  name:              Luc Geurts
  url:               https://twitter.com/lgeurts
  email:             luc.geurts@gmail.com

# Custom vars
version:             1.0.0
github:              repo: github.com/lgeurts/lgeurts.github.io
