# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true #not used since Jekyll v3.0

# Setup
title:               Luc Geurts
tagline:             'AWS, Linux, Windows Server, Xperf, and coding'
description:         'Musings of a former (Platforms) PFE.'
url:                 http://lgeurts.github.io
baseurl:             ''
plugins: 			 [jekyll-paginate]
paginate:            5
paginate_path: 		 "page:num"

# About/contact
author:
  name:              Luc Geurts
  url:               https://twitter.com/lgeurts
  email:             luc.geurts@gmail.com

# Custom vars
version:             1.0.0
repo:                github.com/lgeurts/lgeurts.github.io
